export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" /></head>

      <body>{children}</body>
    </html>
  )
}
